### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [emberian/evdev#65]
Regressed since de2c4e026d1e. CC @unrelentingtech

```rust
$ rustc -vV
rustc 1.58.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.58.1
LLVM version: 13.0.0

$ cargo build
[...]
   Compiling evdev v0.11.4 (/tmp/evdev)
error[E0432]: unresolved imports `libc::ff_effect`, `libc::input_absinfo`, `libc::input_id`, `libc::input_keymap_entry`, `libc::uinput_setup`
 --> src/sys.rs:2:12
  |
2 | use libc::{ff_effect, input_absinfo, input_id, input_keymap_entry, uinput_setup};
  |            ^^^^^^^^^  ^^^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `uinput_setup` in the root
  |            |          |              |         |
  |            |          |              |         no `input_keymap_entry` in the root
  |            |          |              no `input_id` in the root
  |            |          no `input_absinfo` in the root
  |            no `ff_effect` in the root

error[E0425]: cannot find value `EV_CNT` in crate `libc`
   --> src/constants.rs:46:43
    |
46  |     pub(crate) const COUNT: usize = libc::EV_CNT;
    |                                           ^^^^^^ help: a constant with a similar name exists: `AF_CNT`
    |
   ::: /home/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.119/src/unix/bsd/freebsdlike/mod.rs:862:1
    |
862 | pub const AF_CNT: ::c_int = 21;
    | ------------------------------- similarly named constant `AF_CNT` defined here

error[E0425]: cannot find value `INPUT_PROP_CNT` in crate `libc`
  --> src/constants.rs:90:43
   |
90 |     pub(crate) const COUNT: usize = libc::INPUT_PROP_CNT;
   |                                           ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `REL_CNT` in crate `libc`
   --> src/constants.rs:116:43
    |
116 |     pub(crate) const COUNT: usize = libc::REL_CNT;
    |                                           ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `ABS_CNT` in crate `libc`
   --> src/constants.rs:185:43
    |
185 |     pub(crate) const COUNT: usize = libc::ABS_CNT;
    |                                           ^^^^^^^ help: a constant with a similar name exists: `AF_CNT`
    |
   ::: /home/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.119/src/unix/bsd/freebsdlike/mod.rs:862:1
    |
862 | pub const AF_CNT: ::c_int = 21;
    | ------------------------------- similarly named constant `AF_CNT` defined here

error[E0425]: cannot find value `SW_CNT` in crate `libc`
   --> src/constants.rs:232:43
    |
232 |     pub(crate) const COUNT: usize = libc::SW_CNT;
    |                                           ^^^^^^ help: a constant with a similar name exists: `AF_CNT`
    |
   ::: /home/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.119/src/unix/bsd/freebsdlike/mod.rs:862:1
    |
862 | pub const AF_CNT: ::c_int = 21;
    | ------------------------------- similarly named constant `AF_CNT` defined here

error[E0425]: cannot find value `LED_CNT` in crate `libc`
   --> src/constants.rs:260:43
    |
260 |     pub(crate) const COUNT: usize = libc::LED_CNT;
    |                                           ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MSC_CNT` in crate `libc`
   --> src/constants.rs:285:43
    |
285 |     pub(crate) const COUNT: usize = libc::MSC_CNT;
    |                                           ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SND_CNT` in crate `libc`
   --> src/constants.rs:340:43
    |
340 |     pub(crate) const COUNT: usize = libc::SND_CNT;
    |                                           ^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
  --> src/device_state.rs:12:44
   |
12 |     pub(crate) abs_vals: Option<Box<[libc::input_absinfo; AbsoluteAxisType::COUNT]>>,
   |                                            ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
  --> src/device_state.rs:89:46
   |
89 |     pub fn abs_vals(&self) -> Option<&[libc::input_absinfo]> {
   |                                              ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
 --> src/inputid.rs:5:37
  |
5 | pub struct InputId(pub(crate) libc::input_id);
  |                                     ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
 --> src/inputid.rs:7:17
  |
7 | impl From<libc::input_id> for InputId {
  |                 ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
 --> src/inputid.rs:9:23
  |
9 |     fn from(id: libc::input_id) -> Self {
  |                       ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
  --> src/inputid.rs:13:18
   |
13 | impl AsRef<libc::input_id> for InputId {
   |                  ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
  --> src/inputid.rs:15:32
   |
15 |     fn as_ref(&self) -> &libc::input_id {
   |                                ^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_id` in crate `libc`
  --> src/inputid.rs:36:26
   |
36 |         Self::from(libc::input_id {
   |                          ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
  --> src/raw_stream.rs:36:27
   |
36 | const ABSINFO_ZERO: libc::input_absinfo = libc::input_absinfo {
   |                           ^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_absinfo` in crate `libc`
  --> src/raw_stream.rs:36:49
   |
36 | const ABSINFO_ZERO: libc::input_absinfo = libc::input_absinfo {
   |                                                 ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
  --> src/raw_stream.rs:39:40
   |
39 | pub(crate) const ABS_VALS_INIT: [libc::input_absinfo; AbsoluteAxisType::COUNT] =
   |                                        ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
  --> src/raw_stream.rs:56:15
   |
56 |     id: libc::input_id,
   |               ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
  --> src/raw_stream.rs:69:37
   |
69 |     pub(crate) event_buf: Vec<libc::input_event>,
   |                                     ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/raw_stream.rs:401:67
    |
401 |         let num_read = bytes_read as usize / mem::size_of::<libc::input_event>();
    |                                                                   ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
   --> src/raw_stream.rs:429:54
    |
429 |     pub fn get_abs_state(&self) -> io::Result<[libc::input_absinfo; AbsoluteAxisType::COUNT]> {
    |                                                      ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
   --> src/raw_stream.rs:430:34
    |
430 |         let mut abs_vals: [libc::input_absinfo; AbsoluteAxisType::COUNT] = ABS_VALS_INIT;
    |                                  ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
   --> src/raw_stream.rs:466:31
    |
466 |         abs_vals: &mut [libc::input_absinfo; AbsoluteAxisType::COUNT],
    |                               ^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_keymap_entry` in crate `libc`
   --> src/raw_stream.rs:518:32
    |
518 |         let mut keymap = libc::input_keymap_entry {
    |                                ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_keymap_entry` in crate `libc`
   --> src/raw_stream.rs:531:32
    |
531 |         let mut keymap = libc::input_keymap_entry {
    |                                ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_keymap_entry` in crate `libc`
   --> src/raw_stream.rs:555:32
    |
555 |         let mut keymap = libc::input_keymap_entry {
    |                                ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_keymap_entry` in crate `libc`
   --> src/raw_stream.rs:574:32
    |
574 |         let mut keymap = libc::input_keymap_entry {
    |                                ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `KEY_CNT` in crate `libc`
  --> src/scancodes.rs:19:43
   |
19 |     pub(crate) const COUNT: usize = libc::KEY_CNT;
   |                                           ^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_absinfo` in crate `libc`
   --> src/sync_stream.rs:262:54
    |
262 |     pub fn get_abs_state(&self) -> io::Result<[libc::input_absinfo; AbsoluteAxisType::COUNT]> {
    |                                                      ^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/sync_stream.rs:414:51
    |
414 |                           let ev = InputEvent(libc::input_event {
    |                                                     ^^^^^^^^^^^ not found in `libc`
...
430 | /                 try_compensate!(
431 | |                     time,
432 | |                     start: Key,
433 | |                     KEY,
...   |
438 | |                     |vals, key| vals.contains(key)
439 | |                 );
    | |_________________- in this macro invocation
    |
    = note: this error originates in the macro `try_compensate` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `input_absinfo` in crate `libc`
   --> src/sync_stream.rs:453:29
    |
453 |                     &[libc::input_absinfo],
    |                             ^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/sync_stream.rs:414:51
    |
414 |                           let ev = InputEvent(libc::input_event {
    |                                                     ^^^^^^^^^^^ not found in `libc`
...
447 | /                 try_compensate!(
448 | |                     time,
449 | |                     start: AbsoluteAxisType,
450 | |                     ABSOLUTE,
...   |
455 | |                     |vals, abs| vals[abs.0 as usize].value
456 | |                 );
    | |_________________- in this macro invocation
    |
    = note: this error originates in the macro `try_compensate` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/sync_stream.rs:414:51
    |
414 |                           let ev = InputEvent(libc::input_event {
    |                                                     ^^^^^^^^^^^ not found in `libc`
...
464 | /                 try_compensate!(
465 | |                     time,
466 | |                     start: SwitchType,
467 | |                     SWITCH,
...   |
472 | |                     |vals, sw| vals.contains(sw)
473 | |                 );
    | |_________________- in this macro invocation
    |
    = note: this error originates in the macro `try_compensate` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/sync_stream.rs:414:51
    |
414 |                           let ev = InputEvent(libc::input_event {
    |                                                     ^^^^^^^^^^^ not found in `libc`
...
481 | /                 try_compensate!(
482 | |                     time,
483 | |                     start: LedType,
484 | |                     LED,
...   |
489 | |                     |vals, led| vals.contains(led)
490 | |                 );
    | |_________________- in this macro invocation
    |
    = note: this error originates in the macro `try_compensate` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union/2679 type `input_event` in crate `libc`
   --> src/sync_stream.rs:491:43
    |
491 |                 let ev = InputEvent(libc::input_event {
    |                                           ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/sync_stream.rs:542:24
    |
542 |     event_buf: &[libc::input_event],
    |                        ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/sync_stream.rs:544:20
    |
544 | ) -> (Result<libc::input_event, bool>, Option<usize>) {
    |                    ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
  --> src/uinput.rs:19:22
   |
19 |     id: Option<libc::input_id>,
   |                      ^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `uinput_setup` in crate `libc`
   --> src/uinput.rs:115:32
    |
115 |         let mut usetup = libc::uinput_setup {
    |                                ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `UINPUT_MAX_NAME_SIZE` in crate `libc`
   --> src/uinput.rs:117:29
    |
117 |             name: [0; libc::UINPUT_MAX_NAME_SIZE],
    |                             ^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `UINPUT_MAX_NAME_SIZE` in crate `libc`
   --> src/uinput.rs:126:46
    |
126 |         assert!(name_bytes.len() + 1 < libc::UINPUT_MAX_NAME_SIZE);
    |                                              ^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_id` in crate `libc`
   --> src/uinput.rs:133:25
    |
133 | const DEFAULT_ID: libc::input_id = libc::input_id {
    |                         ^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_id` in crate `libc`
   --> src/uinput.rs:133:42
    |
133 | const DEFAULT_ID: libc::input_id = libc::input_id {
    |                                          ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `uinput_setup` in crate `libc`
   --> src/uinput.rs:146:39
    |
146 |     fn new(file: File, usetup: &libc::uinput_setup) -> io::Result<Self> {
    |                                       ^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/lib.rs:131:29
    |
131 | pub struct InputEvent(libc::input_event);
    |                             ^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/lib.rs:184:26
    |
184 |         InputEvent(libc::input_event {
    |                          ^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `input_event` in crate `libc`
   --> src/lib.rs:202:26
    |
202 |         InputEvent(libc::input_event {
    |                          ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/lib.rs:211:17
    |
211 | impl From<libc::input_event> for InputEvent {
    |                 ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/lib.rs:212:24
    |
212 |     fn from(raw: libc::input_event) -> Self {
    |                        ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/lib.rs:217:18
    |
217 | impl AsRef<libc::input_event> for InputEvent {
    |                  ^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `input_event` in crate `libc`
   --> src/lib.rs:218:32
    |
218 |     fn as_ref(&self) -> &libc::input_event {
    |                                ^^^^^^^^^^^ not found in `libc`

error[E0282]: type annotations needed
  --> src/uinput.rs:35:17
   |
35 |             id: None,
   |                 ^^^^ cannot infer type for type parameter `T` declared on the enum `Option`

Some errors have detailed explanations: E0282, E0412, E0422, E0425, E0432.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `evdev` due to 55 previous errors
```

**Comment by coolreader18** [comment]
Well, that makes sense, evdev is a linux API.

**Comment by coolreader18** [comment]
Oh wait it's a regression, I see. Would it make sense to add the type definitions and everything to `libc`? I didn't even realize evdev could be run on FreeBSD.

**Comment by jeff-hiner** [comment]
This is probably a bug or omission in libc upstream. Perhaps a feature-gated definition that is present on some BSDs but not all.

**Comment by unrelentingtech** [comment]
Is it even right for the libc crate to include these on Linux? uapi headers technically aren't related to *the c library*…

**Comment by Ralith** [comment]
The libc crate isn't specifically "the C standard library", but rather OS API bindings in general.
